release:
  stage: deploy
  allow_failure: false
  image: wemakeservices/kira-release:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    REGISTRY: "registry.gitlab.com"
    # Uncomment to entirely skip gitlab docker registry releases:
    # KIRA_RELEASE_SKIP_DOCKER: 'true'

    # Build local image to be released to gitlab registry,
    # modify it to suite your needs as you wish.
    # We only care about the name of the image:
    KIRA_RELEASE_EXEC_CONFIG: |
      {"prepareCmd": "docker build -t \"$REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME\" ."}
  script:
    # Copy the release configuration:
    - cp /release/release.config.js .
    # Release everything!
    - semantic-release
  only:
    - master
  # Uncomment to make the release process manual:
  # when: manual
